apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-auth
  namespace: bookshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-auth
  template:
    metadata:
      labels:
        app: redis-auth
    spec:
      containers:
      - name: redis-auth
        image: redis:5-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 6379
        envFrom:
          - configMapRef:
              name: redis-config-auth
          - secretRef:
              name: redis-secret-auth
        volumeMounts:
          - mountPath: /data
            name: redis-auth
      volumes:
      - name: redis-auth
        persistentVolumeClaim:
          claimName: redis-volume-claim-auth