selector:
  app: users # TODO make this work as in example (?)

namespace: bookshop

image:
  name: ashonuyak/microservices-user
  tag: latest

lifecycle:
  postStart:
    exec:
      command: ["npm", "run", "typeorm", "--", "migration:run"]

service:
  ports:
    - name: http
      port: 8080
      targetPort: 3001

ingress:
  path: /user # TODO maybe change to userS here or to user in other names
  port: 8080

configs:
  POSTGRES_TYPE: "postgres"
  POSTGRES_HOST: "postgres-db" # -user
  POSTGRES_PORT: "5432"
  POSTGRES_NAME: "abubadb" # "postgres-user" # TODO possible issue here # this is db name (?)

  # POSTGRES_DB: abuba

secrets:
  # shared
  POSTGRES_USER: "YWJ1YmE=" # "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "YWJ1YmE=" # "cG9zdGdyZXM="

  # user
  #postgres://abuba:abuba@postgres:5432/postgres-user?sslmode=disable
  #cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlczo6cG9zdGdyZXMtdXNlcjo1NDMyL3Bvc3RncmVzLXVzZXI/c3NsbW9kZT1kaXNhYmxl

  #postgres://abuba:abuba@postgres:5432/abubadb?sslmode=disable
  POSTGRES_URL: "cG9zdGdyZXM6Ly9hYnViYTphYnViYUBwb3N0Z3Jlczo1NDMyL2FidWJhZGI/c3NsbW9kZT1kaXNhYmxl"

  # exist due to inconsistency in variable names
  POSTGRES_USERNAME: "YWJ1YmE=" # "cG9zdGdyZXM="

  # TODO add lifecycle from deployment and remove from template (?)