selector:
  app: users # TODO make this work as in example (?)

namespace: bookshop

image:
  name: melkye/microservices-user # ashonuyak/microservices-user
  tag: latest

lifecycle:
  postStart:
    exec:
      command: ["npm", "run", "typeorm", "--", "migration:run"]

service:
  ports:
    - name: http
      port: 8080
      targetPort: 3001

ingress:
  path: /user
  port: 8080

configs:
  POSTGRES_TYPE: "postgres"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "user"

secrets:
  # shared # TODO try several connections simultaneously
  POSTGRES_USER: "YWJ1YmE=" # "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "YWJ1YmE=" # "cG9zdGdyZXM="

  # user
  # postgres://abuba:abuba@postgres:5432/user?sslmode=disable
  POSTGRES_URL: "cG9zdGdyZXM6Ly9hYnViYTphYnViYUBwb3N0Z3Jlczo1NDMyL3VzZXI/c3NsbW9kZT1kaXNhYmxl"