selector:
  app: email # TODO make this work as in example (?)

namespace: bookshop

image:
  name: ashonuyak/microservices-email
  tag: latest

service:
  ports:
    - name: http
      port: 8080
      targetPort: 3002