selector:
  app: auth # TODO make this work as in example (?)

namespace: bookshop

image:
  name: melkye/microservices-auth # ashonuyak/microservices-auth
  tag: latest

lifecycle:
  postStart:
    exec:
      command: ["npm", "run", "typeorm", "--", "migration:run"]

service:
  ports:
    - name: http
      port: 8080
      targetPort: 3000 

ingress:
  path: /auth
  port: 8080

configs:
  POSTGRES_TYPE: "postgres"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "auth"

  REDIS_HOST: "redis-auth"
  REDIS_PORT: "6379"

  #POSTGRES_DB: abuba
  #REDIS_DB: redis-auth # TODO need redis db or not??

secrets:
  # shared
  POSTGRES_USER: "YWJ1YmE=" # "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "YWJ1YmE=" # "cG9zdGdyZXM="
  
  # auth
  #postgres://abuba:abuba@postgres:5432/auth?sslmode=disable
  POSTGRES_URL: "cG9zdGdyZXM6Ly9hYnViYTphYnViYUBwb3N0Z3Jlczo1NDMyL2F1dGg/c3NsbW9kZT1kaXNhYmxl"

  REDIS_USERNAME: "cmVkaXM="
  REDIS_PASSWORD: "cmVkaXM="
  # redis://redis-auth:6379
  REDIS_URL: "cmVkaXM6Ly9yZWRpcy1hdXRoOjYzNzk="