selector:
  app: auth

image:
  name: melkye/microservices-auth
  tag: latest

lifecycle:
  postStart:
    exec:
      command: ["npm", "run", "typeorm", "--", "migration:run"]

backendconfig:
  healthcheck:
    path: /auth/healthz
    port: 3000 #80

service:
  ports:
    - name: http
      port: 8080
      targetPort: 3000 

configs:
  POSTGRES_TYPE: "postgres"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "auth"

  # TODO do smth with bookshop in var names (and values)
  REDIS_HOST: "redis-auth-master"
  REDIS_PORT: "6379"

secrets:
  # TODO move to common
  # postgres:postgres
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="

  # postgres://postgres:postgres@postgres-db:5432/auth?sslmode=disable
  POSTGRES_URL: "cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlcy1kYjo1NDMyL2F1dGg/c3NsbW9kZT1kaXNhYmxl"

  REDIS_USERNAME: "cmVkaXM="
  REDIS_PASSWORD: "cmVkaXM="

  # redis://redis:redis@redis-auth-master:6379
  REDIS_URL: "cmVkaXM6Ly9yZWRpczpyZWRpc0ByZWRpcy1hdXRoLW1hc3Rlcjo2Mzc5"
  
  JWT_SECRET_ACCESS: "YWNjZXNzYWNjZXNzYWxv"
  JWT_SECRET_REFRESH: "cmVmcmVzaHJlZnJlc2hhbGFsbw=="
  ACCESS_TTL: "NjAw"
  REFRESH_TTL: "NjA0ODAw"
  BCRYPT_SALT_ROUNDS: "MTA="