apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-deployment
  namespace: bookshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger
  template:
    metadata:
      labels:
        app: swagger
    spec:
      containers:
        - name: swagger
          image: ashonuyak/microservices-swagger:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003