apiVersion: v1
kind: Service
metadata:
  name: swagger-service
  namespace: bookshop
  labels:
    app: swagger
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 3003
  selector:
    app: swagger
