apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  #namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  # POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER }}
  # POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD }}