selector:
  app: books # TODO make this work as in example (?)

namespace: bookshop

image:
  name: melkye/books-image
  tag: "2.1"

backendconfig:
  healthcheck:
    path: /books
    port: 80

backendConfig:
  name: 

service:
  ports:
    - name: http
      port: 8080
      targetPort: 80 

ingress:
  path: /books
  port: 8080

configs:
  POSTGRES_DB: "books"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5432"

secrets:
  # TODO move to common
  # postgres:postgres
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="

  # doesn't work
  # # abuba:abuba
  # POSTGRES_USER: "YWJ1YmE="
  # POSTGRES_PASSWORD: "YWJ1YmE="