postgresql:
  fullnameOverride: postgres-auth # TODO doesn't work
  global:
    postgresql:
      auth:
        postgresPassword: "adminabuba"
        username: "abuba"
        password: "abuba"
        database: "abuba"
      service:
        ports:
          postgresql: "5432" ###
    primary:
      persistence:
        size: 2Gi # TODO make this valuable
        mountPath: /var/lib/postgresql/data
  
redis:
  #password: "abuba"
  auth:
    password: "abuba"
  master:
    persistence:
      size: 2Gi
      path: /data
    service:
      ports:
        redis: 6379
  # TODO maybe also need replicas
  # TODO remove namespace




  # fullnameOverride: postgres
  # # postgresqlDatabase: "demo"
  # # postgresqlUsername: "demo"
  # # postgresqlPassword: "demo"
  # # postgresqlPostgresPassword: "demo"
  # persistence:
  #   size: 1Gi
  #   mountPath: /var/lib/postgresql/data