apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  namespace: bookshop
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: email    
  template:
    metadata:
      labels:
        app: email    
    spec:
      containers:
        - name: email
          image: ashonuyak/microservices-email:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002