apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: bookshop
  labels:
    app: email
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 3002
  selector:
    app: email
