postgresql:
  fullnameOverride: postgres-db
  global:
    postgresql:
      auth:
        postgresPassword: "postgres"
      service:
        ports:
          postgresql: "5432"
  primary:
    persistence:
      size: 1Gi
    initdb:
      scripts:
        init.sql: "CREATE DATABASE \"auth\";CREATE DATABASE \"books\";CREATE DATABASE \"user\";CREATE DATABASE \"orders\";"
  audit:
    logConnections: true
  
redis:
  fullnameOverride: "redis-auth"
  architecture: "standalone" # for not creating replicas
  auth:
    enabled: false
    password: "redis"
  master:
    persistence:
      size: 1Gi
      path: /data
    service:
      ports:
        redis: "6379"

kafka:
  fullnameOverride: kafka
  numPartitions: 3
  autoCreateTopicsEnable: false 
  provisioning:
    enabled: true
    topics:
      - name: email.send
        partitions: 3
      - name: email.failed
        partitions: 3
  persistence:
    size: 1Gi