postgresql:
  fullnameOverride: postgres-db # TODO doesn't work ??? now wotks i guess
  global:
    postgresql:
      auth:
        postgresPassword: "adminabuba"
        username: "abuba"
        password: "abuba"
        database: "abubadb"
      service:
        ports:
          postgresql: "5432" ###
  primary:
    persistence:
      size: 2Gi # TODO make this valuable UPD shifted from global, baybe works now
      mountPath: /var/lib/postgresql/data
  audit:
    logConnections: true
  
redis:
  #password: "abuba"
  auth:
    password: "redis"
  master:
    persistence:
      size: 2Gi
      path: /data
    service:
      ports:
        redis: "6379"
  replica:
    replicaCount: 1
  # TODO set count to 1 to reduce resource util, maybe need more replicas
  # TODO remove namespace

kafka:
  fullnameOverride: kafka       # ім'я сервісу (хост по якому можна звертатись до брокера)
  numPartitions: 3              # кількість розділів визначає скільки консьюмерів може бути в топіка одночасно  
  autoCreateTopicsEnable: false # заборонити автоматичне створення топіків, вони мають визначатись явно, в списку нижче
  provisioning:
    enabled: true               # при запуску будуть створені перелічені топіки
    topics:
     - name: demo