postgresql:
  fullnameOverride: postgres-db
  global:
    postgresql:
      auth:
        postgresPassword: "admin"
        username: "abuba"
        password: "abuba"
      service:
        ports:
          postgresql: "5432"
  primary:
    persistence:
      size: 2Gi
      mountPath: /var/lib/postgresql/data
    # TODO make dbs creation work
    initdb:
      scripts:
        init.sql: |
          CREATE DATABASE "auth" OWNER abuba;
          CREATE DATABASE "books" OWNER abuba;
          CREATE DATABASE "user" OWNER abuba;
  audit:
    logConnections: true
  
redis:
  #password: "abuba" try this in case auth.pass doesn't work
  auth:
    password: "redis"
  master:
    persistence:
      size: 2Gi
      path: /data
    service:
      ports:
        redis: "6379"
  replica:
    replicaCount: 1
    persistence:
      size: 2Gi
  # TODO set count to 1 to reduce resource util, maybe need more replicas
  # TODO remove namespace

kafka:
  fullnameOverride: kafka       # ім'я сервісу (хост по якому можна звертатись до брокера)
  numPartitions: 3              # кількість розділів визначає скільки консьюмерів може бути в топіка одночасно  
  autoCreateTopicsEnable: false # заборонити автоматичне створення топіків, вони мають визначатись явно, в списку нижче
  provisioning:
    enabled: true               # при запуску будуть створені перелічені топіки
    topics:
     - name: demo
  persistence:
    size: 2Gi